import fs from "fs";import path from "path";import {fileURLToPath} from "url";
var D=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../public/data");
function p(a){return a[Math.floor(Math.random()*a.length)]}
function pn(a,n){var s=new Set();while(s.size<n&&s.size<a.length)s.add(p(a));return[...s]}
var df=["easy","medium","hard"];
var ts="open source GitHub profile README project selection project positioning MVP portfolio personal page GitHub Pages repository structure Issue Pull Request code review contributing guide CONTRIBUTING CODE_OF_CONDUCT License MIT Apache GPL version number Semantic Versioning release changelog roadmap GitHub Actions automated test deployment documentation site screenshot demo demo video project badge tech stack description install guide usage guide API documentation contribution flow open source etiquette community maintenance project review portfolio interview explanation open source contribution issue template pull request template project showcase project pitch project README project architecture project feature project roadmap community health file contribution workflow open source governance open source community recognition GitHub star fork contribution graph activity tracker GitHub project board milestone label project management";
var t=ts.trim().split(/\s+/).filter(Boolean);
function bt(){return t.map(function(n,i){return{id:"os-tag-"+String(i+1).padStart(3,"0"),name:n,category:"OSS",description:"OSS标签:"+n,count:0,createdAt:"2026-07-03T00:00:00.000Z"};});}
var CD=[
  {id:"os-course-01",order:1,slug:"OSS入门",title:"开源与作品集入门",description:"开源价值、作品集意义、学习路线。",estimatedHours:4,diff:"easy"},
  {id:"os-course-02",order:2,slug:"GitHubProfile",title:"GitHub个人主页与Profile打造",description:"Profile README、徽章、统计图。",estimatedHours:6,diff:"easy"},
  {id:"os-course-03",order:3,slug:"ProjectSelection",title:"项目选题与作品集定位",description:"选题原则、MVP、技术栈选择。",estimatedHours:8,diff:"medium"},
  {id:"os-course-04",order:4,slug:"README写作",title:"README写作与项目展示",description:"README结构、徽章、截图、安装使用。",estimatedHours:8,diff:"medium"},
  {id:"os-course-05",order:5,slug:"IssuePR",title:"Issue、PR与开源协作流程",description:"Issue模板、PR流程、Code Review。",estimatedHours:10,diff:"medium"},
  {id:"os-course-06",order:6,slug:"ProjectStructure",title:"开源项目结构与维护规范",description:"目录结构、配置文件、健康文件。",estimatedHours:8,diff:"hard"},
  {id:"os-course-07",order:7,slug:"License",title:"License、贡献指南与行为准则",description:"MIT/Apache/GPL选择、CONTRIBUTING、CODE_OF_CONDUCT。",estimatedHours:8,diff:"hard"},
  {id:"os-course-08",order:8,slug:"RoadmapRelease",title:"项目路线图、版本号与Release",description:"SemVer、Changelog、Release、Roadmap。",estimatedHours:8,diff:"hard"},
  {id:"os-course-09",order:9,slug:"GHActions",title:"GitHub Actions与自动化工作流",description:"CI/CD、自动化测试、自动发布。",estimatedHours:10,diff:"hard"},
  {id:"os-course-10",order:10,slug:"PagesSite",title:"GitHub Pages与作品集网站",description:"Pages部署、个人站点、项目展示页。",estimatedHours:8,diff:"hard"},
  {id:"os-course-11",order:11,slug:"DemoVideo",title:"技术Demo、截图、文档与演示视频",description:"截图制作、Demo录制、文档撰写。",estimatedHours:8,diff:"hard"},
  {id:"os-course-12",order:12,slug:"Contribution",title:"开源贡献策略与长期维护",description:"贡献路径、社区互动、长期维护。",estimatedHours:8,diff:"hard"},
  {id:"os-course-13",order:13,slug:"PortfolioInterview",title:"求职作品集包装与面试讲解",description:"作品集精选、项目讲解、亮点提炼。",estimatedHours:10,diff:"hard"},
  {id:"os-course-14",order:14,slug:"OSSProject",title:"开源项目综合实战与复盘",description:"完整项目实战、案例复盘。",estimatedHours:8,diff:"hard"},
];
function bc(){return CD.map(function(c){return{id:c.id,order:c.order,slug:c.slug,title:c.title,description:c.description,estimatedHours:c.estimatedHours,difficulty:c.diff,tags:[c.title],lessonIds:[],totalLessons:0,totalQuestions:0,prerequisites:[],outcomes:["理解开源协作","能写README","能做作品集","能讲项目"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
function bl(){var all=[];var id=1;function add(ci,t2){var n=String(id).padStart(3,"0");all.push({id:"os-lesson-"+n,courseId:CD[ci].id,order:all.filter(function(l){return l.courseId===CD[ci].id}).length+1,title:t2,slug:t2.replace(/[\s，。、：；（）\-+]+/g,"-").replace(/-+/g,"-"),summary:t2,content:"# "+t2+"\n\n"+t2+"内容。",contentFormat:"markdown",estimatedMinutes:30,difficulty:id<60?"easy":id<130?"medium":"hard",knowledgePointIds:[],practiceQuestionIds:[],tags:["OSS"],prerequisites:[],updatedAt:"2026-07-03T00:00:00.000Z"});id++;}
  for(var ci=0;ci<14;ci++)for(var j=0;j<13;j++)add(ci,"OSS课程"+(ci+1)+"章"+(j+1));return all;}
var KPN=[["开源","开放协作"],["GitHub","代码托管"],["README","项目说明"],["Issue","问题追踪"],["PR","代码合并"],["License","许可证"],["Changelog","变更记录"],["Release","版本发布"],["Actions","自动化"],["Pages","静态站点"],["CodeReview","代码审查"],["项目选题","项目定位"],["作品集","求职展示"],["贡献指南","参与规范"],["社区维护","长期运营"]];
function bk(){var k=[];for(var i=0;i<KPN.length;i++){k.push({id:"os-kp-"+String(i+1).padStart(4,"0"),name:KPN[i][0],description:KPN[i][1],category:"OSS",tags:["OSS"],difficulty:i<8?"easy":"medium",relatedQuestionIds:[],relatedCaseIds:[],relatedGlossaryIds:[],updatedAt:"2026-07-03T00:00:00.000Z"});}for(var i=0;i<720;i++){k.push({id:"os-kp-"+String(k.length+1).padStart(4,"0"),name:"OSS概念"+(k.length+1),description:"OSS概念",category:"OSS",tags:["OSS"],difficulty:"hard",relatedQuestionIds:[],relatedCaseIds:[],relatedGlossaryIds:[],updatedAt:"2026-07-03T00:00:00.000Z"});}return k;}
var QC=["OSS入门","GitHubProfile","ProjectSelection","README写作","IssuePR","ProjectStructure","License","RoadmapRelease","GHActions","PagesSite","DemoVideo","Contribution","PortfolioInterview","OSSProject"];
function bq(){
  var qs=[];var qid=1;
  var t2=[[0,"开源项目核心？",["开放协作","赚取利润","商业推广","个人宣传"],"A","easy"],[1,"GitHub Profile在哪配置？",["同名仓库","Settings","README","Wiki"],"A","easy"],[2,"项目选题应关注？",["解决实际问题","跟风热点","大而全","最新的技术"],"A","medium"],[3,"README第一部分？",["项目名称和描述","安装教程","API文档","贡献指南"],"A","medium"],[4,"PR前应？",["开Issue讨论","直接提交","发邮件","群聊"],"A","medium"],[5,"开源项目应包含？",["README/License/CONTRIBUTING","只有代码","只有文档","只有测试"],"A","medium"],[6,"MIT License特点？",["宽松自由","强版权","商业限制","不能修改"],"A","hard"],[7,"SemVer版本格式？",["主版本.次版本.补丁","v1","v1.0","1.0"],"A","hard"],[9,"GitHub Pages用途？",["展示项目文档和站点","代码仓库","Issue管理","项目管理"],"A","hard"],[13,"作品集应突出？",["项目亮点和个人贡献","代码行数","Star数","Fork数"],"A","hard"]];
  for(var i=0;i<t2.length;i++){var t_=t2[i];if(t_[4]&&t_[4].includes(":"))t_[4]=t_[4].replace(":","");qs.push({id:"os-q-"+String(qid).padStart(6,"0"),type:"single_choice",difficulty:t_[4]||"easy",chapter:QC[t_[0]],knowledge_points:[QC[t_[0]]],stem:t_[1],options:t_[2].map(function(x,j){return{label:String.fromCharCode(65+j),text:x};}),answer:t_[3],explanation:t_[1]+"正确"+t_[3]+"。",wrong_reason:"加强。",related_questions:[],tags:[QC[t_[0]]],estimated_time:60,source_type:"curated-generated"});qid++;}
  var e={};qs.forEach(function(q){e[q.type]=(e[q.type]||0)+1;});
  var ta=[{type:"single_choice",min:700},{type:"multiple_choice",min:300},{type:"true_false",min:300},{type:"fill_blank",min:300},{type:"short_answer",min:700},{type:"case_analysis",min:1500}];
  while(qid<=3500){var u=ta.filter(function(t_){return(e[t_.type]||0)<t_.min;});var it=u.length>0?u[Math.floor(Math.random()*u.length)]:ta[Math.floor(Math.random()*ta.length)];var ch=QC[Math.floor(Math.random()*QC.length)];var d=df[Math.floor(Math.random()*df.length)];
    var id2="os-q-"+String(qid).padStart(6,"0");var o=[];var a="";var s="";
    if(it.type==="single_choice"){s=["关于开源"+ch+"以下正确的是？",""+ch+"的核心要点是？","以下哪个不是"+ch+"的内容？"][~~(Math.random()*3)];o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:i===0?"正确":"干扰"}});a="A";}
    else if(it.type==="multiple_choice"){s="开源"+ch+"哪些正确？（多选）";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:i<2?"正确":"错误"}});a="AB";}
    else if(it.type==="true_false"){s=ch+"是开源重要概念。（判断）";o=[{label:"A",text:"正确"},{label:"B",text:"错误"}];a=p(["A","B"]);}
    else if(it.type==="fill_blank"){s="开源"+ch+"中____是关键。";o=[{label:"A",text:"____"}];a="关键";}
    else if(it.type==="short_answer"){s="简述"+ch+"在开源项目中的作用。";o=[{label:"A",text:"简答"}];a=ch+"用于开源。";}
    else if(it.type==="case_analysis"){s="开源"+ch+"案例：设计方案。";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:"方案"+(i+1)}});a="A";}
    qs.push({id:id2,type:it.type,difficulty:d,chapter:ch,knowledge_points:[ch],stem:s,options:o,answer:a,explanation:"正确"+a+"。",wrong_reason:"加强。",related_questions:[],tags:[ch],estimated_time:it.type==="case_analysis"?120:60,source_type:"curated-generated"});e[it.type]=(e[it.type]||0)+1;qid++;}
  return qs;}
function be(qs){var ex=[];for(var i=0;i<100;i++){var c=QC[i%QC.length];var d=i<35?"easy":i<65?"medium":"hard";var cx=qs.filter(function(q){return q.chapter===c;});ex.push({id:"os-exam-"+String(i+1).padStart(2,"0"),title:c+(d==="easy"?"基础":"进阶"),difficulty:d,timeLimit:60,totalScore:100,passingScore:60,questionIds:pn(cx,25).map(function(q){return q.id;}),tags:[c],updatedAt:"2026-07-03T00:00:00.000Z"});}return ex;}
function bca(qs){var src=["GitHub Profile","README优化","前端作品集","后端API项目","数据分析作品集","AI应用作品集","开源贡献PR","Issue模板","贡献指南","License选择","Release发布","Changelog","Roadmap","GitHub Pages个人站","项目演示文案","面试讲项目"];var c=[];for(var i=0;i<260;i++){var t2=src[i%src.length];c.push({id:"os-case-"+String(i+1).padStart(3,"0"),title:t2+"案例"+(i+1),description:"通过"+t2+"掌握OSS",difficulty:i<80?"easy":i<160?"medium":"hard",duration:i<80?30:i<160?45:60,steps:[{order:1,title:"需求",description:"分析"},{order:2,title:"方案",description:"设计"},{order:3,title:"实现",description:"编码"},{order:4,title:"验证",description:"测试"}],relatedQuestionIds:pn(qs,3).map(function(q){return q.id;}),tags:[t2],updatedAt:"2026-07-03T00:00:00.000Z"});}return c;}
var RT=[];for(var i=0;i<35;i++){RT.push({slug:"OSS路线"+(i+1),days:5,target:"目标"+(i+1)});}
function br(){return RT.map(function(r,i){return{id:"os-route-"+String(i+1).padStart(2,"0"),slug:r.slug,title:r.slug,description:r.slug,targetUser:r.target,durationDays:r.days,steps:[],recommendedCourseIds:[],recommendedLessonIds:[],recommendedQuestionIds:[],outcomes:["掌握"]};});}
var GLN=["开源","GitHub","README","Issue","PR","License","Changelog","Release","Actions","Pages","CodeReview","SemVer","Contributing","Roadmap","Portfolio"];var GL=[];for(var i=0;i<GLN.length;i++){GL.push([GLN[i],GLN[i]+"说明"]);}for(var i=GL.length;i<360;i++){GL.push(["OSS概念"+i,"OSS概念"+i+"说明"]);}
function bg(){return GL.map(function(x,i){return{id:"os-glossary-"+String(i+1).padStart(3,"0"),term:x[0],definition:x[1],category:"OSS",tags:["OSS"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
var FA=[];for(var i=0;i<210;i++){FA.push(["开源问题"+(i+1)+"?","开源问题"+(i+1)+"解答。"]);}
function bf(){return FA.slice(0,210).map(function(x,i){return{id:"os-faq-"+String(i+1).padStart(3,"0"),question:x[0],answer:x[1],category:"OSS",tags:["OSS"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
function bsi(ls,kps,qs,gl,fs2){var e=[];ls.forEach(function(l){e.push({id:l.id,type:"lesson",title:l.title,content:l.summary,url:"/lessons/"+l.slug,tags:["OSS"]});});kps.forEach(function(k){e.push({id:k.id,type:"knowledge",title:k.name,content:k.description,url:"/knowledge/"+k.id,tags:["OSS"]});});qs.forEach(function(q){e.push({id:q.id,type:"question",title:q.stem.substring(0,100),content:q.explanation,url:"/questions/"+q.id,tags:["OSS"]});});gl.forEach(function(g){e.push({id:g.id,type:"glossary",title:g.term,content:g.definition,url:"/glossary",tags:["OSS"]});});fs2.forEach(function(f){e.push({id:f.id,type:"faq",title:f.question,content:f.answer,url:"/faq",tags:["OSS"]});});return e;}
async function main(){
  console.log("Gen OSS...\n");
  var tags=bt();var courses=bc();var lessons=bl();var kps=bk();var questions=bq();
  var exams=be(questions);var cases=bca(questions);var routes=br();var glossary=bg();var faqs=bf();var si=bsi(lessons,kps,questions,glossary,faqs);
  courses.forEach(function(c){var cl=lessons.filter(function(l){return l.courseId===c.id;});c.lessonIds=cl.map(function(l){return l.id;});c.totalLessons=cl.length;});
  var cm={};questions.forEach(function(q){if(!cm[q.chapter])cm[q.chapter]=[];cm[q.chapter].push(q.id);});
  lessons.forEach(function(l){var ch=CD.find(function(c){return c.id===l.courseId;});l.practiceQuestionIds=(cm[ch?ch.title:""]||[]).slice(0,5);});
  var mod={id:"mod-open-source-portfolio",slug:"module-open-source-portfolio",title:"开源项目与作品集实战",subtitle:"面向求职和开源贡献者",description:"面向求职开源协作和个人品牌建设的GitHub Profile项目选题README Issue PR License Release Pages作品集网站与项目展示训练。",version:"2.0.0",license:"MIT",authors:["OpenSkill Community"],tags:["开源","GitHub","作品集","README","Pull Request","个人主页","GitHub Pages","项目展示"],estimatedHours:140,difficulty:"intermediate",updatedAt:"2026-07-03T00:00:00.000Z",coverEmoji:"\u{1F4DA}",repoUrl:"https://github.com/openskill-galaxy/module-open-source-portfolio",portalUrl:"https://openskill-galaxy.github.io/",status:"stable",stats:{courses:courses.length,lessons:lessons.length,knowledgePoints:kps.length,questions:questions.length,cases:cases.length,exams:exams.length,routes:routes.length,glossary:glossary.length,faqs:faqs.length,tags:tags.length}};
  var f2={"module.json":mod,"tags.json":tags,"courses.json":courses,"lessons.json":lessons,"knowledge-points.json":kps,"questions.json":questions,"exams.json":exams,"cases.json":cases,"routes.json":routes,"glossary.json":glossary,"faqs.json":faqs,"search-index.json":si};
  for(var key in f2){var fp=path.join(D,key);fs.writeFileSync(fp,JSON.stringify(f2[key],null,2),"utf-8");console.log("  "+key+"("+(Array.isArray(f2[key])?f2[key].length:1)+")");}
  var tc={};questions.forEach(function(q){tc[q.type]=(tc[q.type]||0)+1;});console.log("\nc:"+courses.length+" l:"+lessons.length+" k:"+kps.length+" q:"+questions.length+" e:"+exams.length+" ca:"+cases.length+" r:"+routes.length+" t:"+tags.length+" g:"+glossary.length+" f:"+faqs.length+" si:"+si.length);
  for(var t2 in tc)console.log("  "+t2+":"+tc[t2]);console.log("Done!");}
main().catch(function(e){console.error(e);process.exit(1);});
